version: '3'
services:
  api:
    build: ./trucks-api-server
    depends_on:
      - db
    environment:
      - DB=mongodb://db:27017/truck-api
      - PORT=8080
      - BASE_URL=http://127.0.0.1:8080/api
      - SUFFIX_URL={ownerId}/relationships/{path}
      - IA_URL=http://ia:2020/ia
    links:
      - finance:finance
      - ia:ia
    ports:
      - "3232:8080"

  finance:
    build: ./microservice-finance
    dns: 8.8.8.8
    depends_on:
      - db
    links:
      - ia:ia
    environment:
      - DB=mongodb://db:27017/truck-api
      - INIT_URL=http://ia:2020/init


  ia:
    build: ./microservice-ia
    dns: 8.8.8.8
    depends_on:
      - db
    environment:
      - DB=mongodb://db:27017/truck-api
      - PORT=2020

  db:
   image: mongo
   ports:
     - "27027:27017"